// ═══════════════════════════════════════════════════════════════════
// DATOS DE PRODUCTOS — MK AROMAS — COLECCIÓN DE AUTOR
// ═══════════════════════════════════════════════════════════════════

export const INITIAL_PRODUCTS = [
    // ─── FEMENINO ───
    {
        id: "f_1",
        name: "Athenea Blossom",
        category: "perfume",
        gender: "femenino",
        price: 65000,
        image: "https://i.ibb.co/YFR35655/athenea-blossom-3d.png",
        notes: { top: "Neroli, Bergamota", heart: "Azahar, Jazmín", base: "Musk, Ámbar" },
        intensity: 4,
        family: "Floral Cítrico",
        occasion: "Día/Noche",
        duration: "12h",
        isNew: true,
        tagline: "Un amanecer siciliano, radiante y eterno."
    },
    {
        id: "f_2",
        name: "Athenea Classique",
        category: "perfume",
        gender: "femenino",
        price: 65000,
        image: "https://i.ibb.co/ccsgYh20/athenea.png",
        notes: { top: "Pera, Mandarina", heart: "Jazmín, Azahar", base: "Vainilla, Café" },
        intensity: 3,
        family: "Floral Oriental",
        occasion: "Noche",
        duration: "10h+",
        tagline: "La elegancia atemporal de París en una gota."
    },
    {
        id: "f_3",
        name: "Cribagge Rouge 540",
        category: "perfume",
        gender: "femenino",
        price: 65000,
        image: "https://i.ibb.co/cXX7FJmk/Chat-GPT-Image-11-ene-2026-03-11-07-p-m.png",
        notes: { top: "Lavanda", heart: "Iris", base: "Sándalo" },
        intensity: 5,
        family: "Oriental",
        occasion: "Noche",
        duration: "10h+",
        isBestseller: true,
        tagline: "El misterio seductor de una noche estrellada."
    },
    {
        id: "f_17",
        name: "My Lady Way Intense",
        category: "perfume",
        gender: "femenino",
        price: 68000,
        image: "https://i.ibb.co/Dq3t09G/Chat-GPT-Image-16-feb-2026-11-53-01-a-m.png",
        notes: { top: "Flor de Azahar", heart: "Tuberosa", base: "Vainilla de Madagascar" },
        intensity: 4,
        family: "Floral Contemporáneo",
        occasion: "Día/Noche",
        duration: "12h",
        tagline: "Un horizonte de posibilidades infinitas y feminidad radiante."
    },
    {
        id: "f_18",
        name: "My Lady Way Floral",
        category: "perfume",
        gender: "femenino",
        price: 72000,
        image: "https://i.ibb.co/N27wHRLt/Chat-GPT-Image-16-feb-2026-11-54-12-a-m.png",
        notes: { top: "Naranja Amarga", heart: "Tuberosa Intensa", base: "Sándalo" },
        intensity: 5,
        family: "Floral Amaderado",
        occasion: "Noche",
        duration: "10h+",
        tagline: "La profundidad de un encuentro inolvidable."
    },
    {
        id: "f_19",
        name: "My Lady Way",
        category: "perfume",
        gender: "femenino",
        price: 68000,
        image: "https://i.ibb.co/twdvzqsn/Chat-GPT-Image-16-feb-2026-11-55-25-a-m.png",
        notes: { top: "Mandarina Verde", heart: "Neroli Luminoso", base: "Almizcle Blanco" },
        intensity: 3,
        family: "Floral Cítrico",
        occasion: "Primavera",
        duration: "8h",
        tagline: "Un ramo fresco bañado por la luz del sol."
    },

    {
        id: "f_9",
        name: "Quantum Black Pink",
        category: "perfume",
        gender: "femenino",
        price: 65000,
        image: "https://i.ibb.co/239WpJMg/Chat-GPT-Image-13-feb-2026-11-35-17-a-m.png",
        notes: { top: "Limón, Menta", heart: "Romero, Lavanda", base: "Almizcle" },
        intensity: 3,
        family: "Cítrico Aromático",
        occasion: "Día",
        duration: "8h",
        tagline: "La brisa fresca de la montaña en tu piel."
    },
    {
        id: "f_22",
        name: "Candy",
        category: "perfume",
        gender: "femenino",
        price: 65000,
        image: "https://i.ibb.co/7qtFZfs/Chat-GPT-Image-27-dic-2025-16-13-33.png",
        notes: { top: "Melocotón", heart: "Ron, Davana", base: "Pachulí" },
        intensity: 4,
        family: "Frutal",
        occasion: "Atardecer",
        tagline: "Dulçura embriagadora y sofisticada."
    },
    {
        id: "f_20",
        name: "Night Treasure",
        category: "perfume",
        gender: "femenino",
        price: 75000,
        image: "https://i.ibb.co/Rkm54tTR/NIGHT-TREASURE.png",
        notes: { top: "Pera", heart: "Orquídea de Vainilla", base: "Incienso, Praliné" },
        intensity: 5,
        family: "Oriental Gourmand",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Un diamante negro de pasión y misterio."
    },
    {
        id: "f_21",
        name: "Midnight Noir",
        category: "perfume",
        gender: "femenino",
        price: 72000,
        image: "https://i.ibb.co/1Y8y89R9/Chat-GPT-Image-17-dic-2025-11-03-43-p-m.png",
        notes: { top: "Pimienta Negra", heart: "Iris", base: "Cuero Negro" },
        intensity: 5,
        family: "Cuero",
        occasion: "Noche",
        duration: "10h+",
        tagline: "La elegancia oscura de la medianoche."
    },
    {
        id: "f_22",
        name: "Bad Girl Prestige",
        category: "perfume",
        gender: "femenino",
        price: 69000,
        image: "https://i.ibb.co/FbnGPMZr/Chat-GPT-Image-17-dic-2025-11-01-26-p-m.png",
        notes: { top: "Canela", heart: "Ámbar", base: "Madera de Oud" },
        intensity: 4,
        family: "Oriental Amaderado",
        occasion: "Invierno",
        duration: "12h+",
        tagline: "Un elixir dorado de calidez y lujo."
    },
    {
        id: "f_23",
        name: "Bad Girl Privee",
        category: "perfume",
        gender: "femenino",
        price: 70000,
        image: "https://i.ibb.co/cc3zdLWm/Chat-GPT-Image-17-dic-2025-10-59-53-p-m.png",
        notes: { top: "Bergamota", heart: "Pachulí", base: "Musgo de Roble" },
        intensity: 5,
        family: "Chipre",
        occasion: "Formal",
        duration: "10h+",
        tagline: "Profundidad y carácter en cada gota."
    },
    {
        id: "f_24",
        name: "Bella Soleil Diamond",
        category: "perfume",
        gender: "femenino",
        price: 66000,
        image: "https://i.ibb.co/QFBM7g5P/Gemini-Generated-Image-8mtr528mtr528mtr.png",
        notes: { top: "Aldehídos", heart: "Jazmín Blanco", base: "Almizcle" },
        intensity: 3,
        family: "Floral Aldehídico",
        occasion: "Día",
        duration: "8h",
        tagline: "Pura, abstracta y etéreamente bella."
    },
    {
        id: "f_25",
        name: "Millionare Lucestra",
        category: "perfume",
        gender: "femenino",
        price: 68000,
        image: "https://i.ibb.co/whmVrcPw/Chat-GPT-Image-27-dic-2025-20-36-49.png",
        notes: { top: "Frambuesa", heart: "Rosa Damascena", base: "Vainilla" },
        intensity: 4,
        family: "Floral Frutal",
        occasion: "Romántico",
        tagline: "La suavidad de pétalos de rosa aterciopelados."
    },
    {
        id: "f_26",
        name: "Optimus Legion",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/dwcfD79P/Chat-GPT-Image-27-dic-2025-20-08-02.png",
        notes: { top: "Notas Marinas", heart: "Lavanda", base: "Cedro" },
        intensity: 3,
        family: "Acuático",
        occasion: "Verano",
        duration: "6h",
        tagline: "La frescura revitalizante del océano profundo."
    },
    {
        id: "f_27",
        name: "Adventure",
        category: "perfume",
        price: 67000,
        image: "https://i.ibb.co/HLBZXBSW/Chat-GPT-Image-27-dic-2025-20-10-37.png",
        notes: { top: "Hierba Cortada", heart: "Gálbano", base: "Vetiver" },
        intensity: 4,
        family: "Verde",
        occasion: "Primavera",
        duration: "8h",
        tagline: "Naturaleza indómita y elegancia verde."
    },
    {
        id: "f_28",
        name: "Wildest Elixir",
        category: "perfume",
        price: 66000,
        image: "https://i.ibb.co/60G9Pf4m/Chat-GPT-Image-27-dic-2025-20-15-27.png",
        notes: { top: "Naranja Sanguina", heart: "Neroli", base: "Ámbar" },
        intensity: 3,
        family: "Cítrico Solar",
        occasion: "Día",
        duration: "8h",
        tagline: "Un rayo de sol capturado en cristal."
    },
    // ─── MASCULINO ───
    {
        id: "f_10",
        name: "Black Quantum green",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/4R8JBhjH/Chat-GPT-Image-16-feb-2026-12-02-08-p-m.png",
        notes: { top: "Rosa, Grosella", heart: "Peonía, Jazmín", base: "Vainilla, Cedro" },
        intensity: 3,
        family: "Floral Frutal",
        occasion: "Tarde",
        tagline: "Un bouquet floral que desafía al frío."
    },
    {
        id: "f_20",
        name: "GH Classic",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/Bm9kw43/Chat-GPT-Image-28-dic-2025-03-45-52.png",
        notes: { top: "Pimienta Rosa", heart: "Rosa de Mayo", base: "Pachulí" },
        intensity: 4,
        family: "Chipre Floral",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Una rosa con espinas, bella y peligrosa."
    },
    {
        id: "f_21",
        name: "Pure YD",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/jZGzRd69/Chat-GPT-Image-27-dic-2025-20-40-33.png",
        notes: { top: "Cereza Negra", heart: "Almendra Amarga", base: "Haba Tonka" },
        intensity: 4,
        family: "Frutal Gourmand",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Tentación frutal irresistible."
    },
    {
        id: "f_24",
        name: "Millionare",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/kgfmdDtG/Chat-GPT-Image-17-dic-2025-21-26-50.png",
        notes: { top: "Bergamota", heart: "Ylang-Ylang", base: "Coco, Ámbar" },
        intensity: 3,
        family: "Floral Ámbar",
        occasion: "Verano",
        duration: "6h",
        tagline: "El sol eterno en una fragancia."
    },
    {
        id: "f_27",
        name: "Black YD",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/39RtgDxn/Chat-GPT-Image-17-dic-2025-19-09-17.png",
        notes: { top: "Té", heart: "Lirio de los Valles", base: "Almizcle, Ante" },
        intensity: 3,
        family: "Almizcle Floral",
        occasion: "Día",
        duration: "8h",
        tagline: "La suavidad del ante blanco."
    },
    {
        id: "m_1",
        name: "YD12 Vip",
        category: "perfume",
        gender: "masculino",
        price: 70000,
        image: "https://i.ibb.co/G4GhYW2N/Chat-GPT-Image-17-dic-2025-10-52-39-p-m.png",
        notes: { top: "Jengibre", heart: "Oud", base: "Cuero" },
        intensity: 5,
        family: "Amaderado",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Poder y magnetismo en estado puro."
    },
    {
        id: "m_1",
        name: "YD12 ",
        category: "perfume",
        gender: "masculino",
        price: 70000,
        image: "https://i.ibb.co/Y7NxrwXq/Chat-GPT-Image-16-feb-2026-12-00-43-p-m.png",
        notes: { top: "Jengibre", heart: "Oud", base: "Cuero" },
        intensity: 5,
        family: "Amaderado",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Poder y magnetismo en estado puro."
    },
    {
        id: "m_1",
        name: "YD12 Night Club",
        category: "perfume",
        gender: "masculino",
        price: 70000,
        image: "https://i.ibb.co/v6h8wKm9/Chat-GPT-Image-16-feb-2026-11-58-15-a-m.png",
        notes: { top: "Jengibre", heart: "Oud", base: "Cuero" },
        intensity: 5,
        family: "Amaderado",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Poder y magnetismo en estado puro."
    },
    {
        id: "m_2",
        name: "Optimus Black",
        category: "perfume",
        gender: "masculino",
        price: 72000,
        image: "https://i.ibb.co/k6sdtDPz/Chat-GPT-Image-17-dic-2025-09-52-36-p-m.png",
        notes: { top: "Canela", heart: "Tabaco", base: "Ámbar" },
        intensity: 4,
        family: "Especiado",
        occasion: "Invierno",
        duration: "12h+",
        tagline: "Un legado de reyes, cálido y profundo."
    },
    {
        id: "f_12",
        name: "Victorius Aqua",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/RGqr0rmw/Chat-GPT-Image-4-ene-2026-17-24-52.png",
        notes: { top: "Cardamomo, Pomelo", heart: "Cedro, Vetiver", base: "Incienso" },
        intensity: 4,
        family: "Amaderado Especiado",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Misterio y elegancia bajo la luna."
    },
    {
        id: "f_14",
        name: "Grand Victorus",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/FL4nM61x/Chat-GPT-Image-16-feb-2026-12-12-33-p-m.png",
        notes: { top: "Lima", heart: "Vetiver, Salvia", base: "Musgo" },
        intensity: 3,
        family: "Amaderado Verde",
        occasion: "Día",
        duration: "8h",
        tagline: "La frescura salvaje de la naturaleza."
    },
    {
        id: "f_11",
        name: "Victorius Intense",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/yFVdmfzG/Chat-GPT-Image-16-feb-2026-12-04-27-p-m.png",
        notes: { top: "Bergamota, Pimienta", heart: "Ámbar, Labdano", base: "Vainilla, Benjuí" },
        intensity: 4,
        family: "Oriental",
        occasion: "Noche",
        duration: "10h+",
        tagline: "El resplandor dorado del ámbar puro."
    },
    {
        id: "f_25",
        name: "Black YD",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/zWdsfdZ7/Chat-GPT-Image-17-dic-2025-19-11-41.png",
        notes: { top: "Palo de Rosa", heart: "Oud, Sándalo", base: "Vainilla" },
        intensity: 4,
        family: "Amaderado",
        occasion: "Otoño",
        tagline: "Madera preciosa y misterio."
    },
    {
        id: "f_26",
        name: "Black YD L'Elixir",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/hJYwxzY2/Chat-GPT-Image-17-dic-2025-19-18-32.png",
        notes: { top: "Frambuesa", heart: "Jazmín", base: "Cuero, Ante" },
        intensity: 5,
        family: "Cuero",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Cuero toscano, suave y salvaje."
    },
    {
        id: "f_25",
        name: "Black YD",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/zWdsfdZ7/Chat-GPT-Image-17-dic-2025-19-11-41.png",
        notes: { top: "Palo de Rosa", heart: "Oud, Sándalo", base: "Vainilla" },
        intensity: 4,
        family: "Amaderado",
        occasion: "Otoño",
        tagline: "Madera preciosa y misterio."
    },
    {
        id: "f_23",
        name: "Millionare Prive",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/tj3G0MW/Chat-GPT-Image-16-feb-2026-12-19-20-p-m.png",
        notes: { top: "Lavanda", heart: "Almendra, Cuero", base: "Haba Tonka" },
        intensity: 5,
        family: "Cuero",
        occasion: "Fiesta",
        duration: "10h+",
        tagline: "Exclusivo, audaz y fabuloso."
    },
    {
        id: "f_13",
        name: "YD12 Skate",
        category: "perfume",
        gender: "masculino",
        price: 65000,
        image: "https://i.ibb.co/0yPGJMyh/Chat-GPT-Image-4-ene-2026-17-26-38.png",
        notes: { top: "Mandarina", heart: "Cuero, Abedul", base: "Tabaco" },
        intensity: 5,
        family: "Cuero",
        occasion: "Invierno",
        duration: "12h+",
        tagline: "Carácter fuerte y sofisticación clásica."
    },

    // ─── UNISEX ───

    // ─── VELAS & HOME ───
    {
        id: "v_1",
        name: "Mist Patagónico",
        category: "home-deco",
        price: 32000,
        image: "https://i.ibb.co/Q72nMGB0/Chat-GPT-Image-15-ene-2026-08-43-38-a-m.png",
        notes: { top: "Pino", heart: "Eucalipto", base: "Madera" },
        intensity: 3,
        family: "Verde",
        occasion: "Hogar",
        duration: "40h",
        tagline: "El respiro fresco del bosque austral en tu hogar."
    },
    {
        id: "h_1",
        name: "Pimienta Home",
        category: "home-deco",
        price: 42000,
        image: "https://i.ibb.co/twC78DrK/Chat-GPT-Image-2-feb-2026-12-43-38.png",
        notes: { top: "Pimienta", heart: "Clavo", base: "Vainilla" },
        intensity: 4,
        family: "Especiado",
        occasion: "Hogar",
        duration: "40h",
        tagline: "Calidez vibrante y acogedora para tu refugio."
    },
    {
        id: "v_2",
        name: "Golden Vanilla",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/5W40m8b0/Chat-GPT-Image-15-ene-2026-07-37-03-a-m.png",
        notes: { top: "Vainilla Bourbon", heart: "Caramelo Salado", base: "Haba Tonka" },
        intensity: 4,
        family: "Gourmand",
        occasion: "Relax",
        duration: "40h",
        tagline: "Un abrazo cálido de dulzura sofisticada y envolvente."
    },
    {
        id: "v_3",
        name: "Jardín de Peonías",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/fYrzwjxs/Chat-GPT-Image-15-ene-2026-07-35-50-a-m.png",
        notes: { top: "Peonía Rosa", heart: "Lichi Fresco", base: "Almizcle Blanco" },
        intensity: 3,
        family: "Floral",
        occasion: "Primavera",
        duration: "8h",
        tagline: "La delicadeza de un jardín secreto en plena floración."
    },
    {
        id: "v_4",
        name: "Ebony Woods",
        category: "vela",
        price: 34000,
        image: "https://i.ibb.co/CsSWZrrY/Chat-GPT-Image-15-ene-2026-07-11-24-a-m.png",
        notes: { top: "Sándalo", heart: "Cedro del Atlas", base: "Cuero" },
        intensity: 5,
        family: "Amaderado",
        occasion: "Invierno",
        duration: "12h+",
        tagline: "Elegancia masculina y calidez de chimenea para tu hogar."
    },
    {
        id: "v_5",
        name: "Citrus Verbena",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/PZ3vx9bj/Chat-GPT-Image-15-ene-2026-07-08-55-a-m.png",
        notes: { top: "Limón Siciliano", heart: "Verbena", base: "Albahaca" },
        intensity: 4,
        family: "Cítrico",
        occasion: "Día",
        duration: "8h",
        tagline: "Energía vibrante que ilumina y purifica el ambiente."
    },
    {
        id: "v_6",
        name: "Bosque Profundo",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/m5QvV8Jk/Chat-GPT-Image-15-ene-2026-08-43-38-a-m.png",
        notes: { top: "Pino Siberiano", heart: "Musgo de Roble", base: "Tierra Húmeda" },
        intensity: 4,
        family: "Verde",
        occasion: "Hogar",
        duration: "40h",
        tagline: "La serenidad inmensa de un bosque antiguo tras la lluvia."
    },
    {
        id: "v_7",
        name: "Midnight Amber",
        category: "vela",
        price: 34000,
        image: "https://i.ibb.co/Q7SKyJN5/Chat-GPT-Image-15-ene-2026-08-32-37-a-m.png",
        notes: { top: "Ámbar Negro", heart: "Incienso", base: "Pachulí" },
        intensity: 5,
        family: "Oriental",
        occasion: "Noche",
        duration: "10h+",
        tagline: "Misterio y sensualidad para veladas inolvidables."
    },
    {
        id: "v_8",
        name: "Cotton Cloud",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/bqQFKTH/Chat-GPT-Image-15-ene-2026-07-41-57-a-m.png",
        notes: { top: "Flor de Algodón", heart: "Lino Fresco", base: "Talco" },
        intensity: 2,
        family: "Fresco",
        occasion: "Mañana",
        tagline: "La pureza y suavidad de sábanas blancas recién lavadas."
    },
    {
        id: "v_9",
        name: "Rosa Damascena",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/fYrzwjxs/Chat-GPT-Image-15-ene-2026-07-35-50-a-m.png",
        notes: { top: "Pétalos de Rosa", heart: "Geranio", base: "Miel" },
        intensity: 4,
        family: "Floral",
        occasion: "Romántico",
        tagline: "Un tributo a la reina de las flores, clásico y eterno."
    },
    {
        id: "v_10",
        name: "Higo del Mediterráneo",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/d4x6fJhZ/Chat-GPT-Image-15-ene-2026-07-18-55-a-m.png",
        notes: { top: "Hojas de Higuera", heart: "Higo Maduro", base: "Madera de Higuera" },
        intensity: 3,
        family: "Frutal Verde",
        occasion: "Verano",
        duration: "6h",
        tagline: "Sofisticación frutal con un toque verde y lechoso."
    },
    {
        id: "v_11",
        name: "Calma de Lavanda",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/V0YcQrx1/Chat-GPT-Image-15-ene-2026-07-16-05-a-m.png",
        notes: { top: "Lavanda Francesa", heart: "Manzanilla", base: "Vainilla Suave" },
        intensity: 3,
        family: "Aromático",
        occasion: "Descanso",
        tagline: "Un santuario de paz y relajación absoluta."
    },
    {
        id: "v_12",
        name: "Tropical Lime",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/TDfsLK6w/Chat-GPT-Image-15-ene-2026-07-35-48-a-m.png",
        notes: { top: "Lima Fresca", heart: "Coco", base: "Verbena" },
        intensity: 4,
        family: "Cítrico Frutal",
        occasion: "Fiesta",
        duration: "10h+",
        tagline: "Un cóctel refrescante en una playa paradisíaca."
    },
    {
        id: "v_13",
        name: "Coconut Beach",
        category: "vela",
        price: 32000,
        image: "https://i.ibb.co/TDfsLK6w/Chat-GPT-Image-15-ene-2026-07-35-48-a-m.png", // Reutiliza imagen tropical
        notes: { top: "Agua de Coco", heart: "Flor de Tiaré", base: "Vainilla" },
        intensity: 3,
        family: "Gourmand Tropical",
        occasion: "Verano",
        duration: "6h",
        tagline: "La cremosidad exótica del coco bajo el sol."
    }
];
